### ISSUE TITLE
why didn't the “bash scripts/semeval.sh” run

### ISSUE THREAD

**Issue by df6dfs** [Facico/MVRE#2]
Excuse me，I just run the command “bash scripts/semeval.sh” ，the terminal display
that “main.py:error:argument --model_class:expected one argument”.

![wx_camera_1728297051645](https://github.com/user-attachments/assets/7ff38451-3bcb-4d4e-a800-1915a97b5267)
![wx_camera_1728296969910](https://github.com/user-attachments/assets/b565ed40-8b73-4db5-b16a-2814ce98652f)

**Comment by Facico** [comment]
Sorry, there was a minor issue when refactoring the code. You can now remove the "--multi_viewer" flag from the script, or you can pull the repository again. The latest changes have removed some debug information and synchronized the version of dependencies.

**Comment by df6dfs** [comment]
thanks
